version: '3.1'

services:
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - '7777:8080'
    environment:
      - 'SWAGGER_JSON=/docs/Pokefight.docs.json'
    volumes:
      - './docs:/docs'
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: root
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    container_name: app
    build: .
    depends_on:
      - db
      - redis
    command: yarn dev
    ports:
      - '3333:3333'
    volumes:
      - .:/home/app
    environment:
      - 'DB_DIALECT=postgres'
      - 'DB_HOST=db'
      - 'DB_USERNAME=pokemon'
      - 'DB_PASSWORD=root'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'WEBHOOK_LINK=https://webhook.site/my-link'
