version: '3.1'

services:
  db_test:
    container_name: db_test
    image: postgres
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_pokeapi']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: test_pokeapi
      POSTGRES_PASSWORD: root
  redis_test:
    container_name: redis_test
    image: redis
    ports:
      - 6379:6379
